# Generated by Django 4.1 on 2022-08-29 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$390000$z2AwuQrMuYmJDymM3KeqN9$pHzsGHxbKt3b/7fpTaFSYAfBEABypwECgQXTI9PI5yE=', max_length=128, verbose_name='password'),
        ),
    ]
