# Generated by Django 4.1 on 2022-08-29 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0002_alter_myuser_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$390000$nUf1hYxKQ5WOnJs1lv9BYh$LD0hboUKi31hQL4AF417Fz6QVXAWmValC8FOfcSovE4=', max_length=128, verbose_name='password'),
        ),
    ]
