# Generated by Django 4.1 on 2022-08-29 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0004_alter_myuser_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$390000$8JxARBUCmJkbPMgiYbyDAG$1fA9u4thllQCRHEjPCKjeiOvqU0TkngsXZqw7mHDavc=', max_length=128, verbose_name='password'),
        ),
    ]
