# Generated by Django 4.1 on 2022-08-31 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0007_bank_branch_bank_account'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bank_branch',
            old_name='bank_name',
            new_name='bank',
        ),
    ]
