# Generated by Django 4.1 on 2022-09-04 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0009_myuser_id_passport_number_alter_myuser_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='id_passport_number',
            field=models.CharField(default=0, max_length=255),
        ),
    ]
