# Generated by Django 4.1 on 2022-09-04 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0010_alter_myuser_id_passport_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='id_passport_number',
        ),
    ]
