# Generated by Django 4.1 on 2022-09-04 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0011_remove_myuser_id_passport_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='id_number',
            field=models.CharField(max_length=256, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='kra_pin',
            field=models.CharField(max_length=256, null=True, unique=True),
        ),
    ]
