# Generated by Django 4.1 on 2022-09-04 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0015_rename_contribution_moneytransfer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moneytransfer',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='myapi.customer'),
        ),
    ]
