# Generated by Django 4.1 on 2022-09-04 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0016_alter_moneytransfer_account'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='balance',
            new_name='money_recieved',
        ),
        migrations.AddField(
            model_name='customer',
            name='money_withdrawn',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
