# Generated by Django 4.1 on 2022-09-04 12:19

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0017_rename_balance_customer_money_recieved_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settlement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.FloatField()),
                ('approved', models.CharField(choices=[('Verified', 'Verified'), ('Pending', 'Pending'), ('Rejected', 'Rejected')], default='Pending', max_length=256)),
                ('status', models.CharField(choices=[('Completed', 'Completed'), ('Pending', 'Pending'), ('Cancelled', 'Cancelled'), ('Failed', 'Failed')], max_length=256, null=True)),
                ('transaction_ref', models.CharField(max_length=256, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('WithdrawalAccount', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='myapi.bank_account')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='myapi.customer')),
            ],
        ),
    ]
