# Generated by Django 4.1 on 2022-09-04 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0019_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank_account',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='category', to='myapi.category'),
        ),
    ]
